---
- name: provisioning first
  import_playbook: provisioning.yml

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: check if /etc/ansible/ansible.cfg is not a symlink
      stat:
        path: /etc/ansible/ansible.cfg
      register: file

    - name: remove the ansible.cfg file if it's file and replace with the symlink
      block:
        - file:
            path: /etc/ansible/ansible.cfg
            state: absent
        - file: 
            src: /vagrant/ansible.cfg
            dest: /etc/ansible/ansible.cfg
            state: link
      when: (not file.stat.exists) or 
            (file.stat.islnk is defined and not file.stat.islnk)

